### ISSUE TITLE
WINE Mappings

### ISSUE THREAD

**Issue by dwma** [Laharah/deluge-uTorrentImport#6]
When I try to use Wine mappings, I get the following error:

```
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/deluge/ui/client.py", line 504, in __call__
    return self.daemon.call(self.base, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/deluge/ui/client.py", line 457, in call
    return defer.maybeDeferred(m, *copy.deepcopy(args), **copy.deepcopy(kwargs))
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 139, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1237, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1099, in _inlineCallbacks
    result = g.send(result)
  File "/home/wma/.config/deluge/plugins/uTorrentImport-2.2.1-py2.7.egg/utorrentimport/core.py", line 239, in begin_import
    
  File "/home/wma/.config/deluge/plugins/uTorrentImport-2.2.1-py2.7.egg/utorrentimport/core.py", line 137, in find_wine_drives
    
exceptions.IndexError: tuple index out of range
```

I use:
Xubuntu 15.04
deluge: 1.3.11
libtorrent: 0.16.18.0
wine-1.7.50

My uTorrent is 2.2.1. I've been using it with Wine straight from Windows, without changing any setting or location, with the help of a couple of mapped drives in Wine that point to their original locations in Windows.

**Comment by Laharah** [comment]
I've pushed a patch into the develop branch, could you give it a test for me?

here's the updated binaries: https://github.com/Laharah/deluge-uTorrentImport/tree/develop/dist

***NOTE:*** don't "save link as...", click the version you need, then hit view raw. There a bug in github that corrupts zip files when you 'save as'

**Comment by dwma** [comment]
Thanks, that error is gone. However, another issue appeared (should I open another ticket?).

The plugin is attaching the correct path to each torrent file to the location of uTorrent's resume.dat file. (I had changed the default .torrent location in uTorrent.)

```
[ERROR   ] 14:15:02 common:70 [uTorrentImport] Could not open torrent /home/wma/.wine/drive_c/users/wma/Application Data/uTorrent/D:\Torrents\file.torrent! skipping...

**Comment by Laharah** [comment]
No, you can keep it in this issue, it's related.

I think I see what's happening, I'll push out another patch for you to try in a minute. I don't have my wine test environment with me, so it might still need work after I try to patch it.

**Comment by Laharah** [comment]
okay, I've pushed a new patch to the develop branch, hopefully this will fix that issue:

https://github.com/Laharah/deluge-uTorrentImport/tree/develop/dist

again, could you give it a test for me. I'm not at home so I can't test it locally :(

**Comment by dwma** [comment]
Sorry for the delay. I tested it and I get the following error:

```
[ERROR   ] 17:41:09 common:70 [uTorrentImport] Could not open torrent /home/wma/.wine/dosdevices/d:\Torrents\file.torrent! skipping...
```

I think this is due to the backslash being used.

**Comment by Laharah** [comment]
That' should have been happening automatically, but I made it explicit.

https://github.com/Laharah/deluge-uTorrentImport/tree/develop/dist

One last shot. If this dosen't fix it I'll have to wait until I can get back to my testing environment and see if I can figure out what's going wrong.

**Comment by dwma** [comment]
Now it succeeded in adding the torrents, but all their names were changed to "home". Also, if I go to the "Files" tab, the whole path, starting from /home is displayed, but that may be an intended effect.

**Comment by Laharah** [comment]
okay, looks like the os.path module really dosen't like mixing and matching path styles

I tried a quick fix to see if I can get the paths to truncate correctly for the added torrents

https://github.com/Laharah/deluge-uTorrentImport/tree/develop/dist

when the torrent's were added were they checked to 100% or were they all at 0% ?

**Comment by dwma** [comment]
They were at 0%, but I didn't check the "Resume" option, so "Force Recheck" was grayed out.

I can't test the latest update because that address leads me to 404 now.

**Comment by Laharah** [comment]
Give it another try, should work again.
https://github.com/Laharah/deluge-uTorrentImport/tree/develop/dist

**Comment by dwma** [comment]
It's working now, thanks!

There are almost 900 torrents and Deluge has been checking them for a couple of hours now, but I think everything went well.

**Comment by Laharah** [comment]
Glad to hear it's working! I'll merge those changes into the main release!

**Comment by dwma** [comment]
Sorry to open this up again, but I just noticed that in the process a bunch of files were deleted :( I can't be more specific because I didn't notice exactly when or how, and I can't determine any particular pattern among the files that were deleted, except perhaps that I was cross seeding them, that is, more than one .torrent files pointed to the same file. This is just as a heads up.

Also, I noticed that the .torrent files seem to be missing the file extension.

**Comment by Laharah** [comment]
Are they deleted, or just missing from the torrent? Did you set them to resume after adding?

The plugin shouldn't have deleted anything, because it doesn't touch the files until it hands control back to deluge.

You should check to see if there's a `home/more/folders/here` somewhere in wherever you download your torrents to, since there might have been a state where deluge had found the files, but then the plugin told deluge to move them to an incorrect location. So long as you didn't tell deluge to 'remove and delete files' afterward, they should still be there. 

As for the .torrent extension, I'm not sure what you mean. Do you mean in the plugin logs? if so that's on purpose.

**Comment by dwma** [comment]
I have set up Deluge to save all .torrent files in a folder. That folder is now filled with the torrent files I have transferred, but all of them are missing the .torrent extension.

In addition to that, the files that were deleted are also in this folder (I don't know why) but they are actually just a copy of the .torrent file with the name of the file that was deleted (the original file is lost). 

So if in uTorrent I had SomeTorrent.torrent that pointed to SomeImage.iso, if Deluge reports the torrent is at 0%, it means that:
* The original SomeImage.iso is lost.
* Inside my .torrent folder I have:
  * A file named SomeTorrent (which is the .torrent file without the extension).
  * A file named SomeTorrent.iso (which is the same torrent file).

As I said, I don't know when exactly the files were deleted. It might be that some bug in Deluge for my particular setup caused it :(

**Comment by Laharah** [comment]
I'm really sorry that happened, but It's gotta be something with your setup. I'm really not sure what it is.

A 0% can also mean that deluge is pointed to the wrong location, but if it's the same as what was in uTorrent before you started using the plugin, the files must have been moved somewhere. Again, the only way it's possible is if it happened during one of the failed bug fixes, and they would only be deleted if you accidentally hit `remove torrent and delete files` when removing the messed up imports.

Have you tried using a `find /home -type f -name SomeTorrent.iso` to see if there's any files moved to a weird spot?

It sounds like deluge was pointed to download to the same folder where the .torrent files were being saved. There's a brief period after the torrent is re-checked, where the torrent can resumed before deluge re-pauses it. And if any data was received during that time, it may have been sent to that folder.  

But I'm not sure about the files missing the .torrent extension. Deluge would be handling that portion of the import. The original .torrent files should still be wherever uTorrent was keeping them, because the plugin opens them read-only. I can only say that the import copies the .torrent files correctly for my test wine setup.

All this has been assuming you're not running deluge as a windows app through WINE, I'm not really sure how that would work out, but imagine you could have left off the `use wine mappings` option if that were the case.

**Comment by dwma** [comment]
No problem, my last few messages were meant just as a heads up. I know the files were definitely lost by looking at the free space in the partition.

**Comment by Laharah** [comment]
damn, sorry about that. I'll keep an eye out for anyone else having a similar thing happen. I'll also do some deeper testing with more wine setups to see if I can replicate any symptoms.

Thanks again for helping debug my plugin, wish you hadn't lost any data, that was one of the things I designed my plugin to prevent :(
